### ISSUE TITLE
Replacing the call to the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [calvinmetcalf/es6-translate#15]
`new Buffer(...)` is deprecated and unsafe. Would it be possible to replace the [one instance](https://github.com/calvinmetcalf/es6-translate/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) of it with `Buffer.from(...)`?

**Comment by calvinmetcalf** [comment]
fixed
